editables:
    entity/game2:
        path: ../../../entity/conan
    graphics/game2:
        path: ../../../graphics/conan
    entityprotos/local:
        path: ../../conan
layout: layout
workspace_generator: cmake
root: entityprotos/local
